# ============================================================================
# Adaptive Minds - Models Configuration
# ============================================================================
# This file defines all models and LoRA adapters for your system.
# Supports: HuggingFace repos, local paths, and custom configurations.
#
# Usage:
#   python manage_models.py --sync     # Download/sync all models
#   python manage_models.py --list     # List configured models
#   python manage_models.py --rebuild  # Rebuild metadata.json
# ============================================================================

# Base Model Configuration
base_model:
  name: "qwen-2.5-7B-instruct"
  source: "huggingface"  # Options: huggingface, local, custom
  huggingface_id: "Qwen/Qwen2.5-7B-Instruct"
  local_path: "./base_model/qwen-2.5-7B-instruct"
  # Alternative: Use local model
  # source: "local"
  # local_path: "/path/to/your/local/model"

# LoRA Adapters Configuration
# Each adapter can be from HuggingFace, local path, or trained by you
lora_adapters:
  
  # Cool LoRA - General purpose with cool personality
  - name: "Cool"
    source: "huggingface"
    huggingface_id: "bunnycore/Qwen-2.5-7b-Cool-lora"
    local_path: "./loras/qwen-2.5-7b-cool-lora"
    description: "Cool and casual assistant with a fun personality"
    system_prompt: "You are a cool, helpful assistant with a fun and engaging personality. Provide clear, detailed responses while maintaining a casual and friendly tone. Give practical advice and examples. Keep responses conversational and relatable."
    keywords: 
      - cool
      - casual
      - fun
      - friendly
      - general
      - chat
      - conversation
      - help
      - question
      - talk
      - discuss
      - explain
      - tell me
      - how are you
      - hello
      - hi
      - greetings
      - thanks
      - please
      - everyday questions
    enabled: true
  
  # Email LoRA - Specialized for email communication
  - name: "Email"
    source: "huggingface"
    huggingface_id: "doubleyyh/email-tuned-qwen2-lora"
    local_path: "./loras/email-tuned-qwen2-lora"
    description: "Email communication expert for professional and personal correspondence"
    system_prompt: "You are an email communication expert. Help users write professional emails, respond to messages, and improve their email etiquette. Provide clear, actionable advice for email composition, tone, and structure. Include examples of well-written emails when appropriate."
    keywords:
      - email
      - communication
      - professional
      - correspondence
      - writing
      - business
      - formal
      - informal
      - etiquette
      - compose
      - reply
      - message
      - letter
      - correspondence
      - business communication
      - personal communication
    enabled: true
    

  # Example 2: Local LoRA (trained by you)
  # Uncomment and configure after training:
  # - name: "YourCustomDomain"
  #   source: "local"
  #   local_path: "./loras/your-custom-lora"
  #   description: "Your custom domain expert"
  #   system_prompt: "You are an expert in..."
  #   keywords:
  #     - your
  #     - domain
  #     - keywords
  #   enabled: true
  
  # Example 3: From a different HuggingFace user
  # - name: "LegalExpert"
  #   source: "huggingface"
  #   huggingface_id: "someuser/legal-llama-lora"
  #   local_path: "./loras/legal-expert"
  #   description: "Legal expert for law-related questions"
  #   system_prompt: "You are a legal expert..."
  #   keywords:
  #     - legal
  #     - law
  #     - contract
  #   enabled: false  # Set to true when ready to use

# Router Configuration
router:
  prompt_template: |
    Analyze this user query and select the most appropriate domain expert to handle it.
    
    Query: "{query}"
    
    Available Domain Experts:
    {domain_list}
    
    Instructions:
    - Analyze the query carefully
    - Consider the main topic and intent
    - Choose the domain expert that best matches the query
    - If unsure or the query is general/casual, choose General
    - Respond with ONLY the domain name ({domain_names})
    
    Selected Domain:

# Metadata
metadata:
  version: "1.1.0"
  last_updated: "2025-10-03"
  description: "LoRA adapter configuration for Adaptive Minds"
  managed_by: "models_config.yaml - Use manage_models.py to modify"
